java_binary(
    name = "http_client",
    srcs = ["HttpClient.java"],
    main_class = "hw2.HttpClient",
)

java_binary(
    name = "threaded_http_server",
    srcs = [
        "ResponseWriter.java",
        "RequestRecords.java",
        "FileHandler.java",
        "RequestReader.java",
        "HttpStatusCode.java",
        "HttpResponse.java",
        "HttpParseException.java",
        "HttpMethod.java",
        "HttpRequest.java",
        "HttpParser.java",
        "ThreadedHttpServer.java",
        "RequestHandler.java",
    ],
    main_class = "hw2.ThreadedHttpServer",
)
